# Generated by Django 3.0.2 on 2020-01-19 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('2b87e3fe-6001-4e48-a344-d62d1ca9d77d'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('Tiny', 'Tiny'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=20)),
                ('friendliness', models.IntegerField()),
                ('trainability', models.IntegerField()),
                ('shedding_amount', models.IntegerField()),
                ('exercise_needs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('195f9f3c-f780-427d-b454-24b2280095f7'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('favorite_food', models.CharField(blank=True, max_length=50, null=True)),
                ('favorite_toy', models.CharField(blank=True, max_length=50, null=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.Breed')),
            ],
        ),
    ]
