# Generated by Django 3.0.2 on 2020-01-26 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('270064c6-00f1-402e-88ba-ac606311fe79'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dog',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('63a5ba68-8c08-4523-b47c-dfef961377e2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
